@baseUrl=http://localhost:3000/api
@resourceName=categories

# Categories

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
content-type: application/json

{
    "name":"Cây độc lạ",
    "urlParam":"cay-doc-la"
}

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/2
content-type: application/json

{
    "name":"Cây dược liệu", 
    "urlParam":"cay-duoc-lieu"
}

###

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2
